services:
  marcoalbarelli.jwt_checker:
      class: Marcoalbarelli\APIBundle\Service\JWTChecker
      arguments:
        - "%secret%"
        - "%jwt_algs%"
  marcoalbarelli.api_user_authenticator:
      class: Marcoalbarelli\APIBundle\Service\APIUserAuthenticator
  marcoalbarelli.api_user_provider:
      class: Marcoalbarelli\APIBundle\Service\APIUserProvider
  marcoalbarelli.api_user_auth_entrypoint:
      class: Marcoalbarelli\APIBundle\Service\APIAuthEntrypoint
      arguments:
        - "%fos_user.firewall_name%"
