security:
    encoders:
        plain: plain
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        in_memory_provider:
            memory:
                users:
        fos_userbundle:
            id: fos_user.user_provider.username
        chain_provider:
            chain:
                providers:          [ in_memory_provider , fos_userbundle ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        admin_area:
            pattern: /admin/
            security: true
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                provider: chain_provider
                csrf_provider: form.csrf_provider
                use_referer: true
            anonymous:    true
            logout:
                path:           /admin/logout
                target:         /

    access_control:
        - { path: ^/admin/login* , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/* , roles: ROLE_ADMIN }
