security:
    encoders:
        plain: plain
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory_provider:
            memory:
                users:
        chain_provider:
            chain:
                providers:          [ in_memory_provider ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        admin_area:
            pattern: /admin/
            security: true
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                provider: chain_provider
                csrf_provider: form.csrf_provider
                use_referer: true
            anonymous:    true
            logout:
                path:           /logout
                target:         /

    access_control:
        - { path: ^/admin/login* , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/* , roles: ROLE_ADMIN }